// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitalConnect_API.Data;

#nullable disable

namespace VitalConnect_API.Migrations
{
    [DbContext(typeof(VT_DbContext))]
    [Migration("20260405200947_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("VitalConnect_API.Models.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AsistenteID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdAsistente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProfesional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacienteID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfesionalID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CitaId");

                    b.HasIndex("AsistenteID");

                    b.HasIndex("PacienteID");

                    b.HasIndex("ProfesionalID");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("VitalConnect_API.Models.DetalleReceta", b =>
                {
                    b.Property<int>("DetalleRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdMedicamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdReceta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleRecetaId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("DetalleReceta");
                });

            modelBuilder.Entity("VitalConnect_API.Models.FichaAtencion", b =>
                {
                    b.Property<int>("FichaAtencionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CitaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAtencion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCita")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FichaAtencionId");

                    b.HasIndex("CitaId");

                    b.ToTable("FichaAtencion");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Medicamento", b =>
                {
                    b.Property<int>("MedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MedicamentoId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FichaAtencionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFicha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.HasKey("RecetaId");

                    b.HasIndex("FichaAtencionId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VitalConnect_API.Models.Asistente", b =>
                {
                    b.HasBaseType("VitalConnect_API.Models.Usuario");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Asistentes", (string)null);
                });

            modelBuilder.Entity("VitalConnect_API.Models.Paciente", b =>
                {
                    b.HasBaseType("VitalConnect_API.Models.Usuario");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("VitalConnect_API.Models.Profesional", b =>
                {
                    b.HasBaseType("VitalConnect_API.Models.Usuario");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculaProfesional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Profesionales", (string)null);
                });

            modelBuilder.Entity("VitalConnect_API.Models.Cita", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Asistente", "Asistente")
                        .WithMany()
                        .HasForeignKey("AsistenteID");

                    b.HasOne("VitalConnect_API.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalConnect_API.Models.Profesional", "Profesional")
                        .WithMany("Citas")
                        .HasForeignKey("ProfesionalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asistente");

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("VitalConnect_API.Models.DetalleReceta", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Medicamento", "Medicamento")
                        .WithMany("DetallesReceta")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalConnect_API.Models.Receta", "Receta")
                        .WithMany("DetallesReceta")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("VitalConnect_API.Models.FichaAtencion", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Receta", b =>
                {
                    b.HasOne("VitalConnect_API.Models.FichaAtencion", "FichaAtencion")
                        .WithMany("Recetas")
                        .HasForeignKey("FichaAtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaAtencion");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Asistente", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("VitalConnect_API.Models.Asistente", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitalConnect_API.Models.Paciente", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("VitalConnect_API.Models.Paciente", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitalConnect_API.Models.Profesional", b =>
                {
                    b.HasOne("VitalConnect_API.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("VitalConnect_API.Models.Profesional", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitalConnect_API.Models.FichaAtencion", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Medicamento", b =>
                {
                    b.Navigation("DetallesReceta");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Receta", b =>
                {
                    b.Navigation("DetallesReceta");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("VitalConnect_API.Models.Profesional", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
